# Generated by Django 4.0.3 on 2022-04-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('peso_luna', models.FloatField(blank=True, null=True)),
                ('peso_marte', models.FloatField(blank=True, null=True)),
                ('distancia_recorrida', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peso_luna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Peso_marte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vel_luz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distancia', models.IntegerField()),
            ],
        ),
    ]
