# Generated by Django 4.0.3 on 2022-04-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Astronauta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vel_luz',
            name='distancia',
            field=models.FloatField(),
        ),
    ]
