# Generated by Django 4.0.3 on 2022-04-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Astronauta', '0002_alter_vel_luz_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauta',
            name='distancia_recorrida',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
